controllers/ReviewsController.php
<?php

namespace app\controllers;

use yii\helpers\Url;

use app\models\Reviews;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;


class ReviewsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['edit'],
                'rules' => [
                    [
                        'actions' => ['logout', 'edit', 'new'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    /*'logout' => ['post'],*/
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /*
     * Methods for work with reviews
     */

    public function actionEdit() {
        $this->layout = 'admin';
        $reviewId = isset($_GET['id']) ? $_GET['id'] : '';
        
        if ($reviewId) {
            $review = Reviews::findOne($reviewId);
            return $this->render('edit', [
                'review' => $review,
            ]);
        }

        return $this->goHome();
    }
    
    public function actionNew() {
        $new = new Reviews();
        $new->time = date('Y-m-d H:i');
        $new->public = 0;
        $new->title = 'Заголовок не указан';
        $new->descr = 'Краткое описание не указано';
        $new->text = 'Введите текст';
        $new->save();

        $this->redirect(Url::toRoute(['edit', 'id' => $new->id]));
    }

    public function actionShow() {
        $reviewId = isset($_GET['id']) ? $_GET['id'] : '';
        $review = Reviews::findOne($reviewId);

        if ($review) {
            return $this->render('show', [
                'title' => $review->title,
                'text' => $this->bb2html($review->text)
            ]);
        }
        
        return $this->goHome();
    }

    /*
     * Help
     */

    private function bb2html($text) {
        $bbcode = array("<", ">",
            "[list]", "[*]", "[/list]",
            "[img]", "[/img]",
            "[b]", "[/b]",
            "[u]", "[/u]",
            "[i]", "[/i]",
            "[s]", "[/s]",
            "[q]", "[/q]",
            "[p]", "[/p]",
            '[color="', "[/color]",
            "[size=\"", "[/size]",
            '[url="', "[/url]",
            "[mail=\"", "[/mail]",
            "[code]", "[/code]",
            '"]');
        $htmlcode = array("&lt;", "&gt;",
            "<ul>", "<li>", "</ul>",
            "<img src=\"", "\">",
            "<b>", "</b>",
            "<u>", "</u>",
            "<i>", "</i>",
            "<strike>", "</strike>",
            "<blockquote>", "</blockquote>",
            "<p>", "</p>",
            "<span style=\"color:", "</span>",
            "<span style=\"font-size:", "</span>",
            '<a href="', "</a>",
            "<a href=\"mailto:", "</a>",
            "<code>", "</code>",
            '">');
        $newtext = str_replace($bbcode, $htmlcode, $text);
        //$newtext = nl2br($newtext);
        return $newtext;
    }

    /*
     * AJAX
     */

    public function actionAjax_save_review() {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            $id = isset($_POST['id']) ? $_POST['id'] : null;
            $public = isset($_POST['public']) ? $_POST['public'] : null;
            $title = isset($_POST['title']) ? $_POST['title'] : null;
            $descr = isset($_POST['descr']) ? $_POST['descr'] : null;
            $text = isset($_POST['text']) ? $_POST['text'] : null;
            $images = isset($_POST['images']) ? $_POST['images'] : null;
            $result = $id && $title && $descr && $text && $images;

            if ($result) {
                $review = Reviews::findOne($id);
                $review->public = $public;
                $review->title = $title;
                $review->descr = $descr;
                $review->text = $text;
                $review->images = implode(',', $images);
                $result = $review->save();
            }

            return [
                'saved' => $result
            ];
        }
    }

    public function actionAjax_change_review_image() {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            $game_id = isset($_POST['game_id']) ? $_POST['game_id'] : $_POST['game_id'];
            $game_image = $_POST['image'];
            $result = $game_id;

            if ($game_id) {
                $review = Reviews::findOne($game_id);
                $review->preview = $game_image;
                $result = $review->save();
            }

            return [
                'result' => $result,
                /*'error'  => $review->getErrors()*/
            ];
        }
    }

}

views/admin/index.php
<?php
$this->registerJsFile('\js\jquery.min.js',  ['position' => yii\web\View::POS_END]);
$this->registerJsFile('\js\admin.js?v=1.1',  ['position' => yii\web\View::POS_END]);
$this->registerCssFile('\css\admin.css?v=1.2');
$this->title = 'Admin panel';

use yii\helpers\Url;
use app\models\Reviews; ?>

<div class="site-index">
    <div class="body-content">
        <input type="hidden" name="_csrf" value="<?=Yii::$app->request->getCsrfToken()?>">
        <ul class="nav nav-tabs">
            <li class="adminSectionChoose active" data-enable="#adminSectionStatistics" role="presentation"><a href="#">Statistics</a></li>
            <li class="adminSectionChoose" data-enable="#adminSectionReviews" role="presentation"><a href="#">Reviews</a></li>
            <li class="adminSectionChoose" data-enable="#adminSectionTopNew" role="presentation"><a href="#">Top and New Games</a></li>
        </ul>
        <br>
        <div class="adminSection" id="adminSectionStatistics">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-responsive table-bordered">
                        <caption>Most popular requests</caption>
                        <thead>
                            <tr>
                                <th>Request</th>
                                <th>Count</th>
                                <!-- <th></th> -->
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($requestsByMonth as $request) { ?>
                                <tr>
                                    <td width="90%"> <?=$request['text']?> </td>
                                    <td width="5%"> <?=$request['count']?> </td>
                                    <!-- <td width="5%"> <a class='requests-delete' data-request="<?=$request['text']?>" href='#'>Delete</a> </td> -->
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-6">
                    <table class="table table-responsive table-bordered">
                        <caption>Most clicked requests</caption>
                        <thead>
                            <tr>
                                <th>Request</th>
                                <th>Count</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($clickedByMonth as $request) { ?>
                                <tr>
                                    <td width="95%"> <?=$request['text']?> </td>
                                    <td width="5%"> <?=$request['count']?> </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered">
                        <caption>Recent requests</caption>
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Text</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($recentRequests as $request) { ?>
                                <tr>
                                    <td width="30%"> <?=$request['time']?> </td>
                                    <td width="70%"> <?=$request['text']?> </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-6">
                    <table class="table table-responsive table-bordered">
                        <caption>Recent clicked requests</caption>
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Game</th>
                                <th>Store</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($recentClickedByMonth as $click) { ?>
                                <tr>
                                    <td width="30%"> <?=$click['time']?> </td>
                                    <td width="60%"> <?=$click['game']?> </td>
                                    <td width="10%"> <?=$click['store']?> </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered">
                        <caption>Most visited stores</caption>
                        <thead>
                            <tr>
                                <th>Store</th>
                                <th>Count</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($storesByMonth as $store) { ?>
                                <tr>
                                    <td width="95%"> <?=$store['name']?> </td>
                                    <td width="5%"> <?=$store['count']?> </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="adminSection" id="adminSectionReviews" hidden>
            <table class="table table-bordered" id="store-table">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Text</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach (Reviews::find()->all() as $review) { ?>
                    <tr>
                        <td width="15%">
                            <a href="<?=Url::toRoute(['reviews/edit', 'id' => $review->id])?>">
                                <img class="img-preview" src="<?=$review->preview ? $review->preview : 'img/previews/blank.png'?>">
                            </a>
                        </td>
                        <td width="85%">
                            <div><?=$review->title?></div>
                            <div><?=$review->descr?></div>
                            <div><?=date("Y-m-d H:i", strtotime($review->time))?></div>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <a class="btn btn-primary pull-right col-sm-1" href="<?=Url::toRoute('reviews/new')?>">Add</a>
        </div>
        <div class="adminSection" id="adminSectionTopNew" hidden>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>№</th>
                        <th>Image</th>
                        <th>Game name</th>
                        <th>Request</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($newGames as $game) { ?>
                        <tr data-game-id="<?=$game->id?>">
                            <td width="10%">
                                <input type="number" class="form-control game-option" data-game-option="idx" value="<?=$game->idx?>">
                            </td>
                            <td width="6%">
                                <img class="img-game changeGameImage" src="<?=$game->img?>">
                            </td>
                            <td width="42%">
                                <input type="text" class="form-control game-option" data-game-option="name" value="<?=$game->name?>">
                            </td>
                            <td width="42%">
                                <input type="text" class="form-control game-option" data-game-option="request" value="<?=$game->request?>">
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
            <form id="uploadImg" hidden>
                <input type="file" id="imgFile" />
            </form>
        </div>
    </div>
</div>