controllers/ReviewsController.php
<?php

namespace app\controllers;

use yii\helpers\Url;

use app\models\Reviews;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;


class ReviewsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['edit'],
                'rules' => [
                    [
                        'actions' => ['logout', 'edit', 'new'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    /*'logout' => ['post'],*/
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /*
     * Methods for work with reviews
     */

    public function actionEdit() {
        $this->layout = 'admin';
        $reviewId = isset($_GET['id']) ? $_GET['id'] : '';
        
        if ($reviewId) {
            $review = Reviews::findOne($reviewId);
            return $this->render('edit', [
                'review' => $review,
            ]);
        }

        return $this->goHome();
    }
    
    public function actionNew() {
        $new = new Reviews();
        $new->time = date('Y-m-d H:i');
        $new->public = 0;
        $new->title = 'Заголовок не указан';
        $new->descr = 'Краткое описание не указано';
        $new->text = 'Введите текст';
        $new->save();

        $this->redirect(Url::toRoute(['edit', 'id' => $new->id]));
    }

    public function actionShow() {
        $reviewId = isset($_GET['id']) ? $_GET['id'] : '';
        $review = Reviews::findOne($reviewId);

        if ($review) {
            return $this->render('show', [
                'title' => $review->title,
                'text' => $this->bb2html($review->text)
            ]);
        }
        
        return $this->goHome();
    }

    /*
     * Help
     */

    private function bb2html($text) {
        $bbcode = array("<", ">",
            "[list]", "[*]", "[/list]",
            "[img]", "[/img]",
            "[b]", "[/b]",
            "[u]", "[/u]",
            "[i]", "[/i]",
            "[s]", "[/s]",
            "[q]", "[/q]",
            "[p]", "[/p]",
            '[color="', "[/color]",
            "[size=\"", "[/size]",
            '[url="', "[/url]",
            "[mail=\"", "[/mail]",
            "[code]", "[/code]",
            '"]');
        $htmlcode = array("&lt;", "&gt;",
            "<ul>", "<li>", "</ul>",
            "<img src=\"", "\">",
            "<b>", "</b>",
            "<u>", "</u>",
            "<i>", "</i>",
            "<strike>", "</strike>",
            "<blockquote>", "</blockquote>",
            "<p>", "</p>",
            "<span style=\"color:", "</span>",
            "<span style=\"font-size:", "</span>",
            '<a href="', "</a>",
            "<a href=\"mailto:", "</a>",
            "<code>", "</code>",
            '">');
        $newtext = str_replace($bbcode, $htmlcode, $text);
        //$newtext = nl2br($newtext);
        return $newtext;
    }

    /*
     * AJAX
     */

    public function actionAjax_save_review() {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            $id = isset($_POST['id']) ? $_POST['id'] : null;
            $public = isset($_POST['public']) ? $_POST['public'] : null;
            $title = isset($_POST['title']) ? $_POST['title'] : null;
            $descr = isset($_POST['descr']) ? $_POST['descr'] : null;
            $text = isset($_POST['text']) ? $_POST['text'] : null;
            $images = isset($_POST['images']) ? $_POST['images'] : null;
            $result = $id && $title && $descr && $text && $images;

            if ($result) {
                $review = Reviews::findOne($id);
                $review->public = $public;
                $review->title = $title;
                $review->descr = $descr;
                $review->text = $text;
                $review->images = implode(',', $images);
                $result = $review->save();
            }

            return [
                'saved' => $result
            ];
        }
    }

    public function actionAjax_change_review_image() {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            $game_id = isset($_POST['game_id']) ? $_POST['game_id'] : $_POST['game_id'];
            $game_image = $_POST['image'];
            $result = $game_id;

            if ($game_id) {
                $review = Reviews::findOne($game_id);
                $review->preview = $game_image;
                $result = $review->save();
            }

            return [
                'result' => $result,
                /*'error'  => $review->getErrors()*/
            ];
        }
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

use app\models\Games;
use app\models\History;
use app\models\Follows;
use app\models\NewGames;
use app\models\Reviews;


class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    private function groupByGame($list)
    {
        $games = [];

        foreach ($list as $store => $data) {
            foreach ($data as $game) {
                $games[$game['name']][] = array_merge(['store' => $store], $game);
            }
        }

        $mergedGames = [];
        foreach ($games as $gameKey1 => $gameData1) {
            $unifiedGameKey1 = mb_strtolower(preg_replace("/[^[:alnum:][:space:]]/u", '', $gameKey1), 'UTF-8');
            foreach ($games as $gameKey2 => $gameData2) {
                $unifiedGameKey2 = mb_strtolower(preg_replace("/[^[:alnum:][:space:]]/u", '', $gameKey2), 'UTF-8');
                if ($unifiedGameKey1 == $unifiedGameKey2) {
                    if ($gameKey1 > $gameKey2) {
                        $mergedGames[$gameKey1] = array_merge($gameData1, $gameData2);
                        unset($games[$gameKey1]);
                        unset($games[$gameKey2]);
                    }
                }
            }
        }

        $games = array_merge($games, $mergedGames);

        $withManyStores = [];
        $withOneStore = [];

        foreach ($games as $game => $stores) {
            if (count($stores) > 1) {
                $withManyStores[$game] = $stores;
            } else {
                $withOneStore[] = array_merge($stores[0], ['name' => $game]);
            }
        }

        return array_merge($withManyStores, ['Unique' => $withOneStore]);
    }

    private function groupByPlatform($list)
    {
        $games = [];

        foreach ($list as $store => $data) {
            foreach ($data as $game) {
                $games[$game['platform']][] = array_merge(['store' => $store], $game);
            }
        }

        $mergedGames = [];
        foreach ($games as $gameKey1 => $gameData1) {
            $unifiedGameKey1 = mb_strtolower(preg_replace("/[^[:alnum:][:space:]]/u", '', $gameKey1), 'UTF-8');
            foreach ($games as $gameKey2 => $gameData2) {
                $unifiedGameKey2 = mb_strtolower(preg_replace("/[^[:alnum:][:space:]]/u", '', $gameKey2), 'UTF-8');
                if ($unifiedGameKey1 == $unifiedGameKey2) {
                    if ($gameKey1 > $gameKey2) {
                        $mergedGames[$gameKey1] = array_merge($gameData1, $gameData2);
                        unset($games[$gameKey1]);
                        unset($games[$gameKey2]);
                    }
                }
            }
        }

        $games = array_merge($games, $mergedGames);

        return $games;
    }

    private function sortGamesByPrice($result)
    {
        foreach ($result as $key => $data) {
            usort($data, function ($a, $b) {
                return $b['price'] - $a['price'];
            });
            $result[$key] = $data;
        }

        return $result;
    }

    private function limitByStore($results, $limit)
    {
        foreach ($results as $key => $data) {
            if (count($data)) {
                $results[$key] = array_slice($data, 0, $limit);
            }
        }
        return $results;
    }

    private function declOfNum($number, $titles)
    {
        $cases = array (2, 0, 1, 1, 1, 2);
        return $titles[ ($number%100 > 4 && $number %100 < 20) ? 2 : $cases[min($number%10, 5)] ];
    }

    private function resultsCount($results) {
        $count = 0;
        foreach ($results as $key => $data) {
            $count += count($data);
        }
        return [
            'total' => 'Всего ' . $this->declOfNum($count, ['найдена: ', 'найдено: ', 'найдено: ']),
            'count' => $count . $this->declOfNum($count, [' игра', ' игры', ' игр'])
        ];
    }

    public function actionIndex()
    {
        $searchRequest = isset($_GET['game']) && strlen($_GET['game']) > 2 ? $_GET['game'] : '';

        $example = '';
        $nothingFound = null;
        $results = [];
        $resultsByPlatform = [];
        $resultsByGame = [];

        if ($searchRequest) {
            History::saveRequest($searchRequest);
            $results = Games::search($searchRequest);
            /*$results = $this->prepareImportIoData($results);*/
            $nothingFound = empty($results);

            if ($results) {
                $results = $this->sortGamesByPrice($results);
                $results = $this->limitByStore($results, 10);
                $resultsByGame = $this->groupByGame($results);
                $resultsByPlatform = $this->groupByPlatform($results);
            }
        } else {
            $searchExamples = History::getMostPopularRequests();
            if ($searchExamples) {
                $example = $searchExamples[rand(0, max(count($searchExamples) - 1, 0))]['text'];
            }
        }

        return $this->render('index', [
            'request' => $searchRequest,
            'example' => $example,
            'nothingFound' => $nothingFound,
            'results' => $results,
            'resultsByGame' => $resultsByGame,
            'resultsByPlatform' => $resultsByPlatform,
            'resultsCount' => $this->resultsCount($results),
            //'groupBy' => $groupBy,
            //'stores' => Stores::find()->all(),
            'topRequests' => History::getMostPopularRequests(),
            'newGames' => NewGames::sorted(),
            'lastReviews' => Reviews::lastReviews()
        ]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $this->redirect(Yii::$app->urlManager->createUrl("admin/index"));
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /*
     * AJAX
     */

    public function actionAjax_save_follow()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            
            $text = isset($_POST['text']) ? $_POST['text'] : null;
            $game = isset($_POST['game']) ? $_POST['game'] : null;
            $platform = isset($_POST['platform']) ? $_POST['platform'] : null;
            $store = isset($_POST['store']) ? $_POST['store'] : null;
            $price = isset($_POST['price']) && is_numeric($_POST['price']) ? intval($_POST['price']) : null;
            $result = $text && $game && $platform && $store && $price;

            if ($result) {
                $result = Follows::add($text, $game, $platform, $store, intval($price));
            }

            return [
                'saved' => $result
            ];
        }
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
$this->registerJsFile('/js/jquery.min.js',  ['position' => yii\web\View::POS_END]);
$this->registerJsFile('/js/search.js?v=1.7',  ['position' => yii\web\View::POS_END]);
$this->registerCssFile("/css/mainPage.css?v=1.0");
$this->title = 'Найди дешевые ключи steam, origin, uplay!';
/*echo '<pre>';
echo var_dump($results);
echo '</pre>';
die();*/

use yii\helpers\Url; ?>

<?php
    if (YII_ENV_PROD) {
        include_once("analytics.php");
    }
?>

<div class="container">
    <form class="search-form" role="form">
        <div class="div-game input-group">
            <input name="game" type="text" id="search-request" placeholder="Например: <?=$example?>" value="<?=$request?>"/>
            <span class="input-group-btn search-button-span">
                <button class="search-button" type="submit">Найти</button>
            </span>
        </div>
        <div class="info">
            <div class="div-top-new">
                <div class="div-top">
                    <h1>Топ запросов</h1>
                    <?php foreach ($topRequests as $index => $request) { ?>
                        <div class="div-top-row">
                            <?=$index + 1?>. <a class="top-request" href="#"><?=$request['text']?></a>
                        </div>
                    <?php } ?>
                </div>
                <div class="div-new">
                    <h1>Рекомендации</h1>
                    <div class="div-new-table">
                        <?php foreach ($newGames as $game) { ?>
                            <div class="div-new-game new-game" data-request="<?=$game->request?>">
                                <img class="img-game" src="<?=$game->img?>">
                                <div class="div-game-caption"><?=$game->name?></div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<?php if (Yii::$app->session->hasFlash('unSubscribe')) { ?>
    <div class="container">
        Вы отписались от рассылки!
    </div>
<?php } elseif (Yii::$app->session->hasFlash('deleteGame')) { ?>
    <div class="container">
        Игра удалена из списка отслеживаемых!
    </div>
<?php } ?>
<?php if ($nothingFound === true) { ?>
    <div class="container">
        <h1 class="h1-nothing-found">Ни чего не найдено</h1>
    </div>
<?php } ?>
<!--
ИЗБАВИТСЯ ОТ H1 ВЕЗДЕ.
-->
<?php if (!$nothingFound && $results) { ?>
<div class="container">
    <div class="results-info">
        <div class="count">
            <?=$resultsCount['total'] . ' ' . $resultsCount['count']?>
        </div>
        <div class="sort">
            Сортировать по:
            <a class="sort-option" data-toggle="#results-by-store" href="#">магазину</a>,
            <a class="sort-option" data-toggle="#results-by-game" href="#">игре</a>,
            <a class="sort-option" data-toggle="#results-by-platform" href="#">платформе</a>
        </div>
    </div>
    <!-- GROUP BY STORES -->
    <div class="results" id="results-by-store">
        <?php foreach ($results as $store => $data) { ?>
            <div class="div-results-section">
                <h1><?=$store?></h1>
                <table class="table table-results" id="store-table">
                    <thead>
                        <tr>
                            <th width="75%">Игра</th>
                            <th width="15%">Платформа</th>
                            <th width="10%">Цена</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($data as $game) { ?>
                            <tr class="selectable"
                                data-url="<?=$game['url']?>"
                                data-partner-url="<?=isset($game['partner_url']) ? $game['partner_url'] : ''?>"
                                data-store="<?=$store?>"
                                data-game="<?=$game['name']?>"
                                data-platform="<?=$game['platform']?>"
                                data-price="<?=$game['price']?>"
                            >
                                <td> <a class="game-url" href="<?=isset($game['partner_url']) ? $game['partner_url'] : $game['url']?>" target="_blank"> <?=$game['name']?> </a> </td>
                                <td class="td-platform"> <?= $game['platform'] == "Unknown" ? "Неизвестно" : $game['platform'] ?> </td>
                                <td class="td-price"> <?= $game['price'] != -1 ? $game['price'] . " руб." : "" ?> </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        <?php } ?>
    </div>
    <!-- GROUP BY GAME -->
    <div class="results" id="results-by-game" hidden>
        <?php
            $unique = [];
            if (isset($resultsByGame['Unique'])) {
                $unique = $resultsByGame['Unique'];
                unset($resultsByGame['Unique']);
            }
        ?>
        <?php foreach ($resultsByGame as $game => $_stores) { ?>
            <div class="div-results-section">
                <h1><?=$game?></h1>
                <table class="table table-results" id="game-table">
                    <thead>
                        <tr>
                            <th width="75%">Магазин</th>
                            <th width="15%">Платформа</th>
                            <th width="10%">Цена</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($_stores as $store) { ?>
                            <tr class="selectable"
                                data-url="<?=$store['url']?>"
                                data-partner-url="<?=isset($store['partner_url']) ? $store['partner_url'] : '' ?>"
                                data-store="<?=$store['store']?>"
                                data-game="<?=$game?>"
                                data-platform="<?=$store['platform']?>"
                                data-price="<?=$store['price']?>"
                            >
                                <td> <a class="game-url" href="<?=isset($store['partner_url']) ? $store['partner_url'] : $store['url']?>" target="_blank"> <?= $store['store'] ?> </a> </td>
                                <td class="td-platform"> <?= $store['platform'] == "Unknown" ? "Неизвестно" : $store['platform'] ?> </td>
                                <td class="td-price"> <?= $store['price'] != -1 ? $store['price'] . "&nbsp;руб." : "" ?> </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        <?php } ?>
        <?php if ($unique) { ?>
            <div class="div-results-section">
                <h1>Прочее</h1>
                <table class="table table-results" id="game-table">
                    <thead>
                        <tr>
                            <th width="60%">Игра</th>
                            <th width="15%">Магазин</th>
                            <th width="15%">Платформа</th>
                            <th width="10%">Цена</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($unique as $game) { ?>
                            <tr class="selectable"
                                data-url="<?=$game['url']?>"
                                data-partner-url="<?=isset($game['partner_url']) ? $game['partner_url'] : '' ?>"
                                data-store="<?=$game['store']?>"
                                data-game="<?=$game['name']?>"
                                data-platform="<?=$game['platform']?>"
                                data-price="<?=$game['price']?>"
                            >
                                <td> <a class="game-url" href="<?=isset($game['partner_url']) ? $game['partner_url'] : $game['url']?>" target="_blank"> <?= $game['name'] ?> </a> </td>
                                <td class="td-store"> <?= $game['store'] ?> </td>
                                <td class="td-platform"> <?= $store['platform'] == "Unknown" ? "Неизвестно" : $store['platform'] ?> </td>
                                <td class="td-price"> <?= $game['price'] != -1 ? $game['price'] . "&nbsp;руб." : "" ?> </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        <?php } ?>
    </div>
    <!-- GROUP BY PLATFORM -->
    <div class="results" id="results-by-platform" hidden>
        <?php
            $unknown = [];
            if (isset($resultsByPlatform['Unknown'])) {
                $unknown = $resultsByPlatform['Unknown'];
                unset($resultsByPlatform['Unknown']);
            }
        ?>
        <?php foreach ($resultsByPlatform as $platform => $data) { ?>
            <div class="div-results-section">
                <h1><?=$platform?></h1>
                <table class="table table-results" id="platform-table">
                    <thead>
                        <tr>
                            <th width="75%">Игра</th>
                            <th width="15%">Магазин</th>
                            <th width="10%">Цена</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($data as $game) { ?>
                            <tr class="selectable"
                                data-url="<?=$game['url']?>"
                                data-partner-url="<?=isset($game['partner_url']) ? $game['partner_url'] : '' ?>"
                                data-store="<?=$game['store']?>"
                                data-game="<?=$game['name']?>"
                                data-platform="<?=$platform?>"
                                data-price="<?=$game['price']?>"
                            >
                                <td> <a class="game-url" href="<?=isset($game['partner_url']) ? $game['partner_url'] : $game['url']?>" target="_blank"> <?=$game['name']?> </a> </td>
                                <td class="td-store"> <?= $game['store'] ?> </td>
                                <td class="td-price"> <?= $game['price'] != -1 ? $game['price'] . "&nbsp;руб." : "" ?> </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        <?php } ?>
        <?php if ($unknown) { ?>
            <div class="div-results-section">
            <h1>Неизвестно</h1>
                <table class="table table-results" id="game-table">
                    <thead>
                        <tr>
                            <th width="75%">Игра</th>
                            <th width="15%">Магазин</th>
                            <th width="10%">Цена</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($unknown as $game) { ?>
                            <tr class="selectable"
                                data-url="<?=$game['url']?>"
                                data-partner-url="<?=isset($game['partner_url']) ? $game['partner_url'] : '' ?>"
                                data-store="<?=$game['store']?>"
                                data-game="<?=$game['name']?>"
                                data-platform="<?=$game['platform']?>"
                                data-price="<?=$game['price']?>"
                            >
                                <td> <a class="game-url" href="<?=isset($game['partner_url']) ? $game['partner_url'] : $game['url']?>" target="_blank"> <?= $game['name'] ?> </a> </td>
                                <td class="td-store"> <?= $game['store'] ?> </td>
                                <td class="td-price"> <?= $game['price'] != -1 ? $game['price'] . "&nbsp;руб." : "" ?> </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        <?php } ?>
    </div>
    <div class="div-subscribe">
        <h2>Отслеживай цены на избранные товары!</h2>
        <div class="div-subscribe-form">
            <input type="email" id="subscribe-email" placeholder="Адрес электронной почты">
            <button id="subscribe-button" disabled="true">Отслеживать!</button>
            <div class="div-subscribe-result" id="subscribe-success" hidden> <span class="glyphicon glyphicon-ok"></span> </div>
            <div class="div-subscribe-result" id="subscribe-fail" hidden> <span class="glyphicon glyphicon-remove"></span> </div>
        </div>
    </div>
</div>
<?php } ?>
<div class="container">
    <div class="reviews">
        <h2>Обзоры</h2>
        <div class="reviews-content">
            <?php foreach ($lastReviews as $review) { ?>
                <div class="review">
                    <div class="review-img">
                        <a href="<?=Url::toRoute(['reviews/show', 'id' => $review->id])?>">
                            <img class="img-preview" src="<?=$review->preview?>">
                        </a>
                    </div>
                    <div class="post">
                        <div class="title">
                            <a href="<?=Url::toRoute(['reviews/show', 'id' => $review->id])?>"><?=$review->title?></a>
                        </div>
                        <div class="descr"><?=$review->descr?></div>
                        <div class="footer"><?=date("d.m.Y H:i", strtotime($review->time))?></div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>